### ISSUE TITLE
AttributeError: type object 'TiffFileReader' has no attribute 'load_and_parse_header'

### ISSUE THREAD

**Issue by anuphalarnkar** [tomdoel/ImageSplit#9]
OS: Ubuntu 20.04 LTS
Installation: pip install imagesplit
version: ImageSplit==0.3.1

File used: tiff file
Command: imagesplit --input input_data/b2dc8411c.tiff --out output_data/split_image -s c --format tiff -z --rescale -50 350 --type uchar

Output:
Traceback (most recent call last):
  File "/home/user/programs/anaconda3/envs/detctron2/bin/imagesplit", line 8, in <module>
    sys.exit(main())
  File "/home/user/programs/anaconda3/envs/detctron2/lib/python3.6/site-packages/imagesplit/applications/split_files.py", line 274, in main
    test=args.test)
  File "/home/user/programs/anaconda3/envs/detctron2/lib/python3.6/site-packages/imagesplit/applications/split_files.py", line 43, in split_file
    descriptor_filename, input_file_base, start_index, input_file_base)
  File "/home/user/programs/anaconda3/envs/detctron2/lib/python3.6/site-packages/imagesplit/applications/split_files.py", line 74, in specify_input_descriptors
    generate_input_descriptors(input_file_base, start_index)
  File "/home/user/programs/anaconda3/envs/detctron2/lib/python3.6/site-packages/imagesplit/utils/file_descriptor.py", line 273, in generate_input_descriptors
    format_factory)
  File "/home/user/programs/anaconda3/envs/detctron2/lib/python3.6/site-packages/imagesplit/utils/file_descriptor.py", line 418, in parse_header
    return factory.get_factory(format_string).load_and_parse_header(filename)
AttributeError: type object 'TiffFileReader' has no attribute 'load_and_parse_header'

Other:
I have tried with different TIFF files, even with a smaller 10MB file ranging upto 2GB file size
Error is same. 

Am I giving the correct input? ie; TIFF file or should I be giving some header ??

Regards,
Anup

**Comment by tomdoel** [comment]
Hi,

Thanks for raising the issue. Currently the TIFF support is quite limited (the app was originally developed to process large medical image volumes from MetaIO or vge formats, and TIFF was only an output option). 

I've now added in some of the missing functions to allow very basic TIFF input which should fix the above errors; however this TIFF support is still quite limited as currently the app doesn't properly support colour and won't preserve colourspaces etc. This wasn't clear in the README so I've added a few comments.
